package com.myapp.myapp;


import static com.codename1.ui.CN.*;
import com.codename1.ui.Display;
import com.codename1.ui.Form;
import com.codename1.ui.Dialog;
import com.codename1.ui.Label;
import com.codename1.ui.plaf.UIManager;
import com.codename1.ui.util.Resources;
import com.codename1.io.Log;
import com.codename1.ui.Container;
import com.codename1.ui.FontImage;
import com.codename1.ui.Toolbar;
import java.io.IOException;
import com.codename1.ui.layouts.BoxLayout;
import com.codename1.ui.spinner.Picker;

/**
 * This file was generated by <a href="https://www.codenameone.com/">Codename One</a> for the purpose 
 * of building native mobile applications using Java.
 */
public class MyApplication {

    private Form current;
    private Resources theme;
	 Form f;

    public void init(Object context) {
        theme = UIManager.initFirstTheme("/theme");

        // Enable Toolbar on all Forms by default
        Toolbar.setGlobalToolbar(true);

        // Pro only feature
        Log.bindCrashProtection(true);
    }
    
    public void start() {
        if(current != null){
            current.show();
            return;
        }
//      HomeForm h = new HomeForm();
//        h.getF().show();
 Picker birthday = new Picker();
  f = new Form("Register on AllForKids", BoxLayout.y());
        birthday.setType(Display.PICKER_TYPE_DATE);
        Label birthdayIcon = new Label("", "TextField");
        birthdayIcon.getAllStyles().setFgColor(0xf5bf0a);
        FontImage.setMaterialIcon(birthdayIcon, FontImage.MATERIAL_DATE_RANGE, 3);
        Container c_birthday = new Container(BoxLayout.x());
        c_birthday.addAll(birthdayIcon, birthday);
f.add(c_birthday);
    }
	

    public void stop() {
        current = getCurrentForm();
        if(current instanceof Dialog) {
            ((Dialog)current).dispose();
            current = getCurrentForm();
        }
    }
    
    public void destroy() {
    }

}
